export const mockUsers = [
  { id: 'mock-admin', email: 'admin@playcraft.com', full_name: 'Admin PlayCraft', password: 'admin123', role: 'admin', xp: 0 },
  { id: 'mock-user', email: 'usuario@playcraft.com', full_name: 'Usuario Normal', password: 'user123', role: 'user', xp: 0 },
  { id: 'mock-company', email: 'empresa@playcraft.com', full_name: 'Empresa PlayCraft', password: 'empresa123', role: 'empresa', xp: 0 },
];

export const mockGames = [
  {
    id: 'mock-snake',
    title: 'Snake',
    description: 'El clasico juego de la serpiente. Come, crece y no te choques.',
    full_description: 'Controla la serpiente con las flechas del teclado o WASD. Come la comida roja para crecer y sumar puntos. La comida dorada aparece de vez en cuando y vale 30 puntos. Cada 50 puntos subes de nivel y la serpiente va mas rapida. Elige entre 4 dificultades y activa el modo paredes teletransportadoras si quieres un reto diferente.',
    category: 'arcade',
    game_type: 'builtin',
    game_code: 'snake',
    is_active: true,
    is_multiplayer: false,
    show_leaderboard: true,
    show_achievements: true,
    xp_per_play: 10,
    plays_count: 0,
    rating_sum: 0,
    rating_count: 0,
    publisher: 'PlayCraft',
    created_by: 'admin@playcraft.com',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-pong',
    title: 'Pong',
    description: 'El clasico ping pong arcade. Juega contra la maquina.',
    full_description: 'Mueve tu paleta con el raton o tocando la pantalla. Evita que la pelota pase por tu lado. La velocidad aumenta con cada rebote.',
    category: 'arcade',
    game_type: 'builtin',
    game_code: 'pong',
    is_active: true,
    is_multiplayer: false,
    show_leaderboard: true,
    show_achievements: true,
    xp_per_play: 10,
    plays_count: 0,
    rating_sum: 0,
    rating_count: 0,
    publisher: 'PlayCraft',
    created_by: 'admin@playcraft.com',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-chess',
    title: 'Ajedrez Online',
    description: 'Juega al ajedrez en tiempo real contra otro jugador.',
    full_description: 'Crea una sala y comparte el codigo con tu rival, o unete a una sala existente. El juego sigue las reglas estandar del ajedrez.',
    category: 'estrategia',
    game_type: 'builtin',
    game_code: 'chess-online',
    is_active: true,
    is_multiplayer: true,
    show_leaderboard: true,
    show_achievements: true,
    xp_per_play: 35,
    plays_count: 0,
    rating_sum: 0,
    rating_count: 0,
    publisher: 'PlayCraft',
    created_by: 'admin@playcraft.com',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export function isDatabaseConnectionError(error) {
  return error?.name === 'PrismaClientInitializationError' || String(error?.message || '').includes("Can't reach database server");
}
